"""
Evergreen decision-analysis dashboard + score porter.

Single source of truth:  outputs/dashboard/submissions.json
One command ports every score update to ALL of:
  * the JSON                 (outputs/dashboard/submissions.json)
  * the HTML dashboard       (outputs/dashboard/index.html, self-contained)
  * the memory snapshot      (<memory>/scoreboard.json + a block in the memory md)
  * the agent work log       (a block in SUBMISSIONS.md)

    python -m src.dashboard                    # regenerate everything from JSON
    python -m src.dashboard --set P1=22.90      # set score(s), recompute, regenerate
    python -m src.dashboard --set P1=22.9 --set C2=21.4

A score set on a "queued"/"held" submission flips it to "scored" automatically and
fires its pre-registered decision rule, so the verdict appears the moment the
number lands. Derived fields (axis ratio, delta, verdict) are recomputed on every
run from the raw scores — nothing derived is stored, so the data can never drift.
"""

from __future__ import annotations

import argparse
import json
import os
from datetime import datetime
from typing import Dict, List, Optional

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DASH_DIR = os.path.join(ROOT, "outputs", "dashboard")
JSON_PATH = os.path.join(DASH_DIR, "submissions.json")
HTML_PATH = os.path.join(DASH_DIR, "index.html")
SUBMISSIONS_MD = os.path.join(ROOT, "SUBMISSIONS.md")
DEFAULT_MEMORY_DIR = os.path.join(
    os.path.expanduser("~"),
    ".claude", "projects", "d--ES-DRJ-think-onwards-no-second-guessing", "memory",
)
MEMORY_MD_NAME = "project-no-second-guessing.md"

BLOCK_START = "<!-- SCOREBOARD:START (auto-generated by src/dashboard.py — do not edit by hand) -->"
BLOCK_END = "<!-- SCOREBOARD:END -->"


# ---------------------------------------------------------------------------
# Data
# ---------------------------------------------------------------------------
def load() -> dict:
    with open(JSON_PATH, encoding="utf-8") as fh:
        return json.load(fh)


def save(data: dict) -> None:
    with open(JSON_PATH, "w", encoding="utf-8") as fh:
        json.dump(data, fh, indent=2, ensure_ascii=False)
        fh.write("\n")


def _by_id(subs: List[dict]) -> Dict[str, dict]:
    return {s["id"]: s for s in subs}


def enrich(data: dict) -> dict:
    """Recompute every derived field from raw scores. Pure; mutates copies only."""
    subs = data["submissions"]
    idx = _by_id(subs)

    scored = [s for s in subs if s.get("status") == "scored" and s.get("score") is not None]
    best = max(scored, key=lambda s: s["score"]) if scored else None
    data["meta"]["best_id"] = best["id"] if best else None
    data["meta"]["best_score"] = best["score"] if best else None
    data["meta"]["updated"] = datetime.now().strftime("%Y-%m-%d %H:%M")

    for s in subs:
        anchor = idx.get(s.get("anchor")) if s.get("anchor") else None
        a_score = anchor["score"] if anchor and anchor.get("score") else None
        s["_anchor_score"] = a_score
        s["_ratio"] = None
        s["_delta"] = None
        s["_verdict"] = None
        if s.get("status") == "scored" and s.get("score") is not None and a_score:
            ratio = (s["score"] / a_score) ** 4
            s["_ratio"] = round(ratio, 3)
            s["_delta"] = round(s["score"] - a_score, 2)
            if ratio > 1.02:
                s["_verdict"] = "win"
            elif ratio < 0.98:
                s["_verdict"] = "loss"
            else:
                s["_verdict"] = "flat"
    return data


def apply_sets(data: dict, sets: List[str]) -> None:
    idx = _by_id(data["submissions"])
    for item in sets:
        if "=" not in item:
            raise SystemExit(f"--set expects ID=SCORE, got {item!r}")
        sid, val = item.split("=", 1)
        sid = sid.strip()
        if sid not in idx:
            raise SystemExit(f"unknown submission id {sid!r}; known: {', '.join(idx)}")
        idx[sid]["score"] = float(val)
        idx[sid]["status"] = "scored"
        print(f"  set {sid} = {val} (status -> scored)")


# ---------------------------------------------------------------------------
# HTML rendering (self-contained, no external assets — opens offline anywhere)
# ---------------------------------------------------------------------------
CSS = """
:root{--bg:#0f1420;--card:#171e2e;--ink:#e6ecf5;--mut:#8d9bb5;--line:#26304a;
--win:#34d399;--loss:#f87171;--flat:#fbbf24;--queue:#60a5fa;--held:#6b7280;--accent:#7c9cff}
*{box-sizing:border-box}
body{margin:0;background:var(--bg);color:var(--ink);
font:15px/1.5 -apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif;padding:28px}
.wrap{max-width:1040px;margin:0 auto}
h1{font-size:22px;margin:0 0 2px}
.sub{color:var(--mut);font-size:13px;margin-bottom:20px}
.card{background:var(--card);border:1px solid var(--line);border-radius:14px;padding:18px 20px;margin-bottom:18px}
.grid{display:flex;gap:16px;flex-wrap:wrap}
.kpi{flex:1;min-width:170px}
.kpi .big{font-size:34px;font-weight:700;line-height:1}
.kpi .lbl{color:var(--mut);font-size:12px;text-transform:uppercase;letter-spacing:.05em;margin-top:6px}
h2{font-size:15px;text-transform:uppercase;letter-spacing:.06em;color:var(--mut);margin:6px 0 14px}
.bar-row{display:grid;grid-template-columns:150px 1fr 92px;align-items:center;gap:12px;margin:9px 0}
.bar-row .nm{font-weight:600;font-size:13px}
.bar-row .nm small{display:block;color:var(--mut);font-weight:400}
.track{background:#0c1120;border-radius:7px;height:24px;position:relative;overflow:hidden;border:1px solid var(--line)}
.fill{height:100%;border-radius:6px 0 0 6px;display:flex;align-items:center;justify-content:flex-end;
padding-right:8px;font-size:12px;font-weight:700;color:#0b0f1a}
.lead{position:absolute;top:-3px;bottom:-3px;width:2px;background:var(--accent)}
.lead span{position:absolute;top:-18px;left:-16px;font-size:10px;color:var(--accent);white-space:nowrap}
.chip{display:inline-block;font-size:11px;font-weight:700;padding:2px 8px;border-radius:20px}
.win{background:rgba(52,211,153,.16);color:var(--win)} .loss{background:rgba(248,113,113,.16);color:var(--loss)}
.flat{background:rgba(251,191,36,.16);color:var(--flat)} .queue{background:rgba(96,165,250,.16);color:var(--queue)}
.held{background:rgba(107,114,128,.2);color:#aab4c7}
table{width:100%;border-collapse:collapse;font-size:13px}
th,td{text-align:left;padding:8px 10px;border-bottom:1px solid var(--line)}
th{color:var(--mut);font-size:11px;text-transform:uppercase;letter-spacing:.05em}
td.r,th.r{text-align:right;font-variant-numeric:tabular-nums}
.exp{border:1px solid var(--line);border-radius:11px;padding:14px 16px;margin:12px 0;background:#131a29}
.exp h3{margin:0 0 4px;font-size:15px}
.exp .meta{color:var(--mut);font-size:12px;margin-bottom:10px}
.rule{display:grid;grid-template-columns:96px 1fr;gap:10px;padding:6px 0;border-top:1px dashed var(--line);font-size:13px}
.rule b{color:var(--accent);font-variant-numeric:tabular-nums}
.find li{margin:5px 0}
.foot{color:var(--mut);font-size:12px;margin-top:8px}
code{background:#0c1120;padding:2px 6px;border-radius:5px;font-size:12px}
"""

LO, HI = 10.0, 38.0  # score axis for the bars (gap-to-leader visible)


def _esc(s) -> str:
    return (str(s).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;"))


def _fill_pct(score: float) -> float:
    return max(2.0, min(100.0, (score - LO) / (HI - LO) * 100.0))


def _color(verdict: Optional[str]) -> str:
    return {"win": "var(--win)", "loss": "var(--loss)", "flat": "var(--flat)"}.get(verdict, "var(--queue)")


def render_html(data: dict) -> str:
    m = data["meta"]
    subs = data["submissions"]
    best = m.get("best_score")
    leader = m.get("leader_target", 37.0)
    gap_pct = (best / leader * 100.0) if best else 0.0
    lead_x = (leader - LO) / (HI - LO) * 100.0

    scored = [s for s in subs if s.get("status") == "scored" and s.get("score") is not None]
    scored.sort(key=lambda s: (s["date"], s["score"]))
    queued = [s for s in subs if s.get("status") == "queued"]
    held = [s for s in subs if s.get("status") == "held"]

    h: List[str] = []
    h.append("<!doctype html><html lang=en><head><meta charset=utf-8>")
    h.append("<meta name=viewport content='width=device-width,initial-scale=1'>")
    h.append(f"<title>Decision Dashboard — {_esc(m['challenge'])}</title>")
    h.append(f"<style>{CSS}</style></head><body><div class=wrap>")

    # header / KPIs
    h.append(f"<h1>{_esc(m['challenge'])}</h1>")
    h.append(f"<div class=sub>{_esc(m['prize'])} · updated {_esc(m['updated'])} · "
             "single source of truth: <code>outputs/dashboard/submissions.json</code></div>")
    h.append("<div class=card><div class=grid>")
    h.append(f"<div class=kpi><div class=big>{best:.2f}</div><div class=lbl>best public score "
             f"({_esc(m.get('best_id'))})</div></div>")
    h.append(f"<div class=kpi><div class=big>{leader:.0f}</div><div class=lbl>leader target</div></div>")
    h.append(f"<div class=kpi><div class=big>{gap_pct:.0f}%</div><div class=lbl>of the way to the leaders</div></div>")
    h.append(f"<div class=kpi><div class=big>{len(scored)}</div><div class=lbl>scored / "
             f"{len(queued)} queued / {len(held)} held</div></div>")
    h.append("</div></div>")

    # score history bars
    h.append("<div class=card><h2>Score history</h2>")
    for s in scored:
        v = s["score"]
        chip = ""
        if s["_verdict"] and s.get("_ratio"):
            chip = (f"<span class='chip {s['_verdict']}'>{s['_ratio']:.2f}× · "
                    f"{'+' if s['_delta'] >= 0 else ''}{s['_delta']}</span>")
        h.append("<div class=bar-row>")
        h.append(f"<div class=nm>{_esc(s['id'])} <small>{_esc(s['label'])}</small></div>")
        h.append("<div class=track>")
        h.append(f"<div class=fill style='width:{_fill_pct(v):.1f}%;background:{_color(s['_verdict'])}'>{v:.2f}</div>")
        h.append(f"<div class=lead style='left:{lead_x:.1f}%'><span>leaders {leader:.0f}</span></div>")
        h.append("</div>")
        h.append(f"<div class='r'>{chip}</div>")
        h.append("</div>")
    h.append("<div class=foot>Bar fill = score on a 10–38 axis; the vertical mark is the leaderboard front. "
             "Chip = axis-product ratio vs anchor and raw Δ.</div></div>")

    # live experiments
    if queued:
        h.append("<div class=card><h2>Live experiments — pre-registered reads</h2>")
        for s in queued:
            h.append("<div class=exp>")
            h.append(f"<h3>{_esc(s['id'])} · {_esc(s['label'])} "
                     f"<span class='chip queue'>isolates {_esc(s['isolates'])}</span></h3>")
            h.append(f"<div class=meta>vs anchor {_esc(s['anchor'])} = {s['_anchor_score']:.2f} · "
                     f"footage {s.get('footage','—')} · {_esc(s['change'])}</div>")
            for rule in s.get("rules", []):
                h.append(f"<div class=rule><b>{_esc(rule['if'])}</b><span>{_esc(rule['then'])}</span></div>")
            h.append("</div>")
        h.append("</div>")

    # axis decision analysis table
    h.append("<div class=card><h2>Axis decision analysis</h2><table>")
    h.append("<tr><th>id</th><th>change</th><th>isolates</th><th class=r>footage</th>"
             "<th class=r>score</th><th class=r>anchor</th><th class=r>ratio⁴</th><th>verdict</th></tr>")
    order = [s for s in subs if s.get("anchor")]
    order.sort(key=lambda s: (s["date"], s["id"]))
    for s in order:
        ratio = f"{s['_ratio']:.3f}" if s.get("_ratio") else "—"
        score = f"{s['score']:.2f}" if s.get("score") is not None else "<i>pending</i>"
        anch = f"{s['_anchor_score']:.2f}" if s.get("_anchor_score") else "—"
        vlabel = {"win": "helps", "loss": "hurts", "flat": "neutral"}.get(s["_verdict"], s.get("status"))
        vclass = s["_verdict"] or ("queue" if s.get("status") == "queued" else "held")
        h.append(f"<tr><td><b>{_esc(s['id'])}</b></td><td>{_esc(s['change'])}</td>"
                 f"<td>{_esc(s['isolates'])}</td><td class=r>{s.get('footage','—')}</td>"
                 f"<td class=r>{score}</td><td class=r>{anch}</td><td class=r>{ratio}</td>"
                 f"<td><span class='chip {vclass}'>{_esc(vlabel)}</span></td></tr>")
    h.append("</table><div class=foot>ratio⁴ = (score / anchor)⁴ = the axis-product change a single-variable "
             "submission produced. &gt;1 helps, &lt;1 hurts.</div></div>")

    # findings + next
    h.append("<div class=card><h2>What we know</h2><ul class=find>")
    for f in m.get("findings", []):
        h.append(f"<li>{_esc(f)}</li>")
    h.append("</ul>")
    h.append(f"<h2 style='margin-top:16px'>Next action</h2><div>{_esc(m.get('next_action',''))}</div>")
    h.append("<div class=foot>Update with <code>python -m src.dashboard --set ID=SCORE</code> — "
             "ports to the JSON, this dashboard, memory and SUBMISSIONS.md in one shot.</div></div>")

    h.append("</div></body></html>")
    return "".join(h)


# ---------------------------------------------------------------------------
# Markdown block porting (memory md + agent log)
# ---------------------------------------------------------------------------
def _scoreboard_md(data: dict) -> str:
    m = data["meta"]
    rows = ["| id | score | isolates | ratio⁴ | verdict |", "|----|------:|----------|-------:|---------|"]
    for s in data["submissions"]:
        if s.get("score") is None and s.get("status") != "scored":
            continue
        ratio = f"{s['_ratio']:.3f}" if s.get("_ratio") else "—"
        verdict = s.get("_verdict") or s.get("status")
        rows.append(f"| {s['id']} | {s['score']:.2f} | {s['isolates']} | {ratio} | {verdict} |")
    pend = [s for s in data["submissions"] if s.get("status") in ("queued", "held")]
    pend_txt = "; ".join(f"{s['id']} ({s['isolates']}, footage {s.get('footage','—')})" for s in pend)
    return (
        f"**Scoreboard** (auto, updated {m['updated']}) — best **{m['best_score']:.2f}** "
        f"({m['best_id']}); leader target {m['leader_target']:.0f}.\n\n"
        + "\n".join(rows)
        + f"\n\n_Queued/held:_ {pend_txt or '—'}\n\n_Next:_ {m['next_action']}\n"
    )


def update_block(path: str, body: str) -> bool:
    block = f"{BLOCK_START}\n{body}\n{BLOCK_END}"
    if os.path.exists(path):
        with open(path, encoding="utf-8") as fh:
            text = fh.read()
    else:
        return False
    if BLOCK_START in text and BLOCK_END in text:
        pre = text[: text.index(BLOCK_START)]
        post = text[text.index(BLOCK_END) + len(BLOCK_END):]
        text = pre + block + post
    else:
        text = text.rstrip() + "\n\n" + block + "\n"
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(text)
    return True


def write_memory(data: dict, memory_dir: str) -> List[str]:
    done: List[str] = []
    if not os.path.isdir(memory_dir):
        try:
            os.makedirs(memory_dir, exist_ok=True)
            print(f"  created memory dir: {memory_dir}")
        except OSError as exc:
            print(f"  (cannot create memory dir, skipping: {exc})")
            return done
    snap = {
        "updated": data["meta"]["updated"],
        "best_id": data["meta"]["best_id"],
        "best_score": data["meta"]["best_score"],
        "leader_target": data["meta"]["leader_target"],
        "scored": {s["id"]: s["score"] for s in data["submissions"]
                   if s.get("status") == "scored" and s.get("score") is not None},
        "ratios": {s["id"]: s["_ratio"] for s in data["submissions"] if s.get("_ratio")},
        "queued": [s["id"] for s in data["submissions"] if s.get("status") == "queued"],
        "findings": data["meta"]["findings"],
        "next_action": data["meta"]["next_action"],
    }
    snap_path = os.path.join(memory_dir, "scoreboard.json")
    with open(snap_path, "w", encoding="utf-8") as fh:
        json.dump(snap, fh, indent=2, ensure_ascii=False)
    done.append(snap_path)
    md_path = os.path.join(memory_dir, MEMORY_MD_NAME)
    if update_block(md_path, _scoreboard_md(data)):
        done.append(md_path)
    return done


# ---------------------------------------------------------------------------
def main(argv: Optional[List[str]] = None) -> int:
    ap = argparse.ArgumentParser(description="Decision-analysis dashboard + score porter")
    ap.add_argument("--set", action="append", default=[], metavar="ID=SCORE",
                    help="set a submission's public score (repeatable); flips it to scored")
    ap.add_argument("--memory-dir", default=DEFAULT_MEMORY_DIR, help="Claude memory directory")
    args = ap.parse_args(argv)

    data = load()
    if args.set:
        apply_sets(data, args.set)
    data = enrich(data)
    save(data)

    os.makedirs(DASH_DIR, exist_ok=True)
    with open(HTML_PATH, "w", encoding="utf-8") as fh:
        fh.write(render_html(data))
    print(f"  dashboard -> {HTML_PATH}")

    if update_block(SUBMISSIONS_MD, _scoreboard_md(data)):
        print(f"  agent log -> {SUBMISSIONS_MD}")
    for p in write_memory(data, args.memory_dir):
        print(f"  memory    -> {p}")

    best = data["meta"]
    print(f"  best: {best['best_score']} ({best['best_id']})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
